const express = require("express")
const app = express()
const dotenv = require("dotenv")
const morgan = require('morgan')
const userRoute = require('./Routes/userRoutes')
const adminRoute = require('./Routes/adminRoutes')
const productRoute = require('./Routes/productRoutes')
dotenv.config()
require("./db")
app.use(morgan('dev'))
app.use(express.json())
app.use(userRoute)
app.use(adminRoute)
app.use(productRoute)
module.exports = app